l=[]
for i in range(10):
    d={"num":int(input("entrer num :")),"position":input("entrer pos :"),"nom":input("entrer nom :"),"prenom":input("entrer prenom :"),"prix":int(input("entrer prix:")),"equipe":input("entrer equipe:")}
    l.append(d)

cmp=0
# equi=input("donner le nom  d'equipe :")
# for i in range(2):
#     if l[i]["equipe"]==equi:
#         cmp+=1
#         print(l[i]["nom"],l[i]["prenom"])

        
# print("le nombre est ",cmp)


# sal=float(input("entrer le prix que vous voulez :"))
# for i in range(2):
#     if l[i]["prix"]>=sal:
#         print(l[i])

# pg  l[0][prix'
